### PR TITLE
"pwd -P" -> "pwd"

### PR DESCRIPTION
**Pull request by osalbahr**
I just want to run the CI suite

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Hopefully this helps with ublue-os/bluefin#252

### CODE REVIEW

**Comment by osalbahr** [comment]
oh well

**Comment by osalbahr** [comment]
ok again

**Comment by budhajeewa** [comment]
Interested in seeing this merged, as this might allow using Homebrew on Fedora Silverblue.

**Comment by osalbahr** [comment]
> Interested in seeing this merged, as this might allow using Homebrew on Fedora Silverblue.

Thx! It’s an attempt, still trying. I remember it introduced some errors that I didn’t understand. You can try editing with `vim $(which brew)` or your favorite editor and change whatever.

You can always run `brew doctor` for instructions how to roll back.

**Pull request closed without merging**
