### PR TITLE
Test overriding HOMEBREW_PREFIX and HOMEBREW_REPOSITORY

### PR DESCRIPTION
**Pull request by osalbahr**
This PR is for testing purposes only. I will not merge so I can avoid adding the shell script. I will probably just cherry-pick the last two commits, possibly with some modifications.

See Homebrew/brew#15656.

### CODE REVIEW

**Review by rohanssrao — APPROVED** [review]
I tested these changes on an ubuntu:22.04 container with `/home` symlinked to `/var/home`:
```bash
cd $(brew --repository)
git checkout master
curl https://raw.githubusercontent.com/osalbahr/brew/silverbrew-develop/Library/Homebrew/brew.sh > /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh 
brew install xz
```
`xz` successfully installs from the bottle rather than compiling from source.

**Comment by osalbahr** [comment]
> I tested these changes on an ubuntu:22.04 container with `/home` symlinked to `/var/home`:
> 
> ```shell
> cd $(brew --repository)
> git checkout master
> curl https://raw.githubusercontent.com/osalbahr/brew/silverbrew-develop/Library/Homebrew/brew.sh > /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh 
> brew install xz
> ```
> 
> `xz` successfully installs from the bottle rather than compiling from source.

Thx! The changes worked for me too locally, and in `homebrew/core` and `ubuntu` containers.

**Comment by osalbahr** [comment]
- #4

**Comment by osalbahr** [comment]
#4

**Pull request closed without merging**
