### PR TITLE
Update silverbrew-fedora-toolbox.sh

### PR DESCRIPTION
**Pull request by rohanssrao**
- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by osalbahr** [comment]
Thx! Which containers did you test this on to be 3-reproducible so far?

**Comment by osalbahr** [comment]
Thx! Which containers did you test this on to be 3-reproducible so far? If you’re testing on `podman run -it fedora-toolbox` I will test on `ubuntu`.

**Comment by rohanssrao** [comment]
I tested it on fedora-toolbox.

**Comment by osalbahr** [comment]
LGTM. Thank you!

**Comment by osalbahr** [comment]
Wait why did I close it

**Comment by osalbahr** [comment]
I thought I merged it

**Pull request merged**
